services:
  keyclub_backend:
    build: ./backend
    volumes:
      - ./keyclub_photos:/backend/photos
      - ./key.json:/backend/key.json
      - ./db.sqlite3:/backend/db.sqlite3
      - ./banner.json:/backend/banner.json
    env_file:
      - .env
    expose:
      - 8000
    command: pipenv run uvicorn backend.main:app --port 8000 --host 0.0.0.0

  keyclub_frontend:
    build: ./frontend
    expose:
      - 3000
    command: node build

  keyclub_proxy:
    image: caddy:alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./keyclub_photos:/gallery
    depends_on:
#      - keyclub_backend
      - keyclub_frontend
    ports:
      - 80:80