services:
  keyclub_backend:
    build: ./backend
    volumes:
      - ./keyclub_photos:/backend/photos
      - ./key.json:/backend/key.json
      - ./db.sqlite3:/backend/db.sqlite3
      - ./banner.json:/backend/banner.json
    env_file:
      - .env
    expose:
      - 8000
    networks:
      - local
    command: pipenv run uvicorn backend.main:app --port 8000 --host 0.0.0.0
  keyclub_frontend:
    build: ./frontend
    expose:
      - 3000
    networks:
      - local
    command: node build
  keyclub_proxy:
    container_name: keyclub_proxy
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./keyclub_photos:/gallery
    depends_on:
      - keyclub_backend
      - keyclub_frontend
    ports:
      - 80:80
    networks:
      - local

networks:
  local: