services:
  keyclub_backend:
    build: ./backend
    volumes:
      - keyclub_photos:/app/photos
    env_file:
      - .env
    expose:
      - 8000
    networks:
      - local
    command: pipenv run uvicorn main:app --port 8000 --host 0.0.0.0
  keyclub_frontend:
    build: ./frontend
    volumes:
      - keyclub_photos:/photos
    depends_on:
      - keyclub_backend
#    expose:
#      - 80
    networks:
      - local
    # V for testing only V
    ports:
      - 80:80

volumes:
  keyclub_photos:

networks:
  local: